# Generated by Django 4.2.6 on 2024-02-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_patientappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='time_slot',
            field=models.CharField(choices=[('7-8', '7-8'), ('9-10', '9-10'), ('10-11', '10-11'), ('11-12', '11-12'), ('12-13', '12-13'), ('13-14', '13-14'), ('15-16', '15-16'), ('17-18', '17-18'), ('19-20', '19-20'), ('21-22', '21-22')], default='7-8', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_date',
            field=models.DateField(),
        ),
    ]
