# Generated by Django 4.2.6 on 2024-02-27 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_patientappointment_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='schedule',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.schedule'),
        ),
    ]
